== Property-Based Testing, enfin pour tout le monde

Avec Java 8, le Property-based testing devient enfin naturel et bien outillé ! Inventé pour Haskell et popularisé en Scala, cette technique est puissante pour tester, mais surtout pour découvrir les invariants et symétries qui vont simplifier le design et la modélisation, et contribuer à une Living Documentation".

Cette université a pour objectif de vous faire découvrir cette technique dans le but de l’utiliser à votre retour au bureau. Nous montrerons de nombreux exemples de propriétés et d’heuristiques pour vous aider à les identifier dans votre contexte, avec un mini atelier en séance pour vous y mettre sans attendre. Nous montrerons les outils et nous ferons le lien avec d’autres outils et techniques tels que le Type System, les Fuzzers, TDD, BDD et bien entendu DDD. Si vous vous intéressez au test et au design sous toutes leurs formes, alors vous aimerez le Property-Based Testing !

* QuickCheck
* Complement de TU
* Test compression
* Quick win properties suggest design

Properties are guessing until we speak to Business